### ISSUE TITLE
For the prod we should checkout out to the latest tag

### ISSUE THREAD

**Issue by axilleas** [satnogs/satnogs-ansible#2]

**Comment by comzeradd** [comment]
So for the dev environments we should just checkout the master branch.

For the prod we should checkout out to the latest tag. I think Ansible git module doesn't have an easy way to do that. Here is [relevant discussion](http://stackoverflow.com/a/29157519).

For both dev and prod let's deploy manually for the first iteration.

**Comment by comzeradd** [comment]
I'd also suggest we implement stages first to have not db and network online. This anyway seems easier task than production deployments.

**Comment by comzeradd** [comment]
The only thing left here is to figure out a way to get the latest tag in a dynamic way.

**Comment by comzeradd** [comment]
I made some changes at 37cc3de13b674bea7683ec1aff7c7aae6f7a2f2e that allows us to pass the production tags via command line.
